source 'https://github.com/CocoaPods/Specs.git'
platform :osx, '10.12'
use_frameworks!
project '/Users/gra/Documents/Tapp/Tapp.xcodeproj'
target 'Tapp' do
    pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'AlamofireImage'
    pod 'ObjectMapper'
    pod 'SwiftWebSocket'
    pod 'Charts'
    pod 'Locksmith'
    pod 'FlatButton'
    pod 'PromiseKit'
    pod 'PlaybackSlider'
    pod 'FirebaseOSX'
end
